/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/

LOAD_SERVER TestServerSymbianExcludeUsb

START_TESTCASE USB-INC-ROMCONFIG-004
//! @SYMTestCaseID USB-INC-ROMCONFIG-004
//! @SYMTestCaseDesc RDevUsbcClient::Open should succeed on a standard Techview ROM
//! @SYMREQ 5414
//! @SYMTestType CIT
//! @SYMTestPriority 3
//! @SYMTestStatus Implemented
//! @SYMTestActions Call RDevUsbcClient::Open(0)
//! @SYMTestExpectedResults Returns KErrNone
RUN_TEST_STEP 10 TestServerSymbianExcludeUsb USB_ROMCONFIG_004 c:\testdata\usbromconfig\UsbRomConfig.ini UsbIncluded
END_TESTCASE USB-INC-ROMCONFIG-004
