/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/

// Run all the USB_INC_ROMCONFIG_* tests
// Expects a standard ROM to be built i.e. SYMBIAN_EXCLUDE_USB has NOT been specified

RUN_SCRIPT c:\scripts\usbromconfig\USB_INC_ROMCONFIG_001.script

RUN_SCRIPT c:\scripts\usbromconfig\USB_INC_ROMCONFIG_002.script

RUN_SCRIPT c:\scripts\usbromconfig\USB_INC_ROMCONFIG_003.script

RUN_SCRIPT c:\scripts\usbromconfig\USB_INC_ROMCONFIG_004.script
