/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/

LOAD_SERVER TestServerSymbianExcludeUsb

START_TESTCASE USB-ROMCONFIG-003
//! @SYMTestCaseID USB-ROMCONFIG-003
//! @SYMTestCaseDesc RCommServ::LoadCommModule should fail for ACM csy on a SYMBIAN_EXCLUDE_USB ROM
//! @SYMREQ 5414
//! @SYMTestType CIT
//! @SYMTestPriority 1
//! @SYMTestStatus Implemented
//! @SYMTestActions Call RCommServ::LoadCommModule("ECACM")
//! @SYMTestExpectedResults Returns KErrNotFound, as ecacm.csy has been removed from ROM
RUN_TEST_STEP 10 TestServerSymbianExcludeUsb USB_ROMCONFIG_003 c:\testdata\usbromconfig\UsbRomConfig.ini UsbExcluded
END_TESTCASE USB-ROMCONFIG-003
